### ISSUE TITLE
Generar el pkl y el training

### ISSUE THREAD

**Issue by lmquijano** [gibinaghi/cientificas_de_datos#4]
Escribir el requirements.txt
Estructurar el preprocessing
Estructurar el modelado
Estructurar el postprocessing
Testear lo implementado

**Comment by lmquijano** [comment]
Separamos a las tareas en diferentes issues

**Comment by alemkarina** [comment]
listo el trining, pkl bajo el nombre spam_clf_v1.pkl

**Comment by alemkarina** [comment]
listo el training, pkl bajo el nombre  spam_clf_v1.pkl
